name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.14.0'

      - name: Install dependencies (server)
        working-directory: ./server
        run: npm install

      - name: Generate Drizzle schema
        working-directory: ./server
        run: npm run db:generate

      - name: Run migrations
        working-directory: ./server
        run: npm run db:migrate

      - name: Build server
        working-directory: ./server
        run: npm run build

      - name: Install dependencies (web)
        working-directory: ./web
        run: npm install

      - name: Build web
        working-directory: ./web
        run: npm run build

      - name: Deploy to production
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          port: ${{ secrets.PORT }}
          genai_key: ${{ secrets.GENAI_API_KEY }}
          database_url: ${{ secrets.DATABASE_URL }}
        run: |
          curl "$deploy_url"