name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start services with Docker Compose
        run: docker compose up --build -d

      - name: Wait for services to be healthy
        run: |
          sleep 15
          docker compose ps

      - name: Deploy to production
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          port: ${{ secrets.PORT }}
          genai_key: ${{ secrets.GENAI_API_KEY }}
          database_url: ${{ secrets.DATABASE_URL }}
        run: |
          curl "$deploy_url"